      - name: Build APK (arm,arm64)
        run: |
          # Hapus flag -silent agar kita bisa lihat log error jika gagal
          $HOME/go/bin/fyne-cross android \
            -app-id com.kalender.selamatan \
            -name "Cek Selamatan" \
            -arch=arm,arm64 \
            -ldflags="-s -w" \
            -icon=icon.png
            
      - name: DEBUG - Cari Lokasi APK
        # Langkah ini akan menampilkan lokasi file APK di dalam Log (klik panah di step ini nanti)
        run: find . -name "*.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Selamatan-Premium
          # Tanda **/*.apk artinya cari file APK di folder MANAPUN di seluruh project
          path: "**/*.apk"

