name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Versi stabil untuk fyne-cross

      - name: Install Dependencies
        run: |
          go mod tidy
          go install github.com/fyne-io/fyne-cross@latest

      - name: Build APK (arm64)
        run: |
          # Parameter -icon icon.png adalah kunci agar ikon berubah
          $HOME/go/bin/fyne-cross android \
            -app-id com.richo.kalender \
            -arch arm64 \
            -icon icon.png \
            -silent

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Selamatan-Final
          path: fyne-cross/dist/android/*.apk
