name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: |
          go mod tidy
          go install github.com/fyne-io/fyne-cross@latest

      - name: Build APK (arm64)
        run: |
          $HOME/go/bin/fyne-cross android \
            -app-id com.kalender.selamatan \
            -arch arm,arm64 \
            -name "Cek Selamatan" \
            -ldflags="-s -w" \
            -icon=icon.png
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Selamatan-Premium
          # Tanda **/*.apk artinya cari file APK di folder MANAPUN di seluruh project
          path: "fyne-cross/dist/**/*.apk"

